apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata-service
          image: rajibrath/metadata-service:v1
          resources:
             limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 40
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 40
            periodSeconds: 3            
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://mysql-service:3306/mydb
            - name: app.version
              value: v3