Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "rajib.vm"
  config.vm.network "private_network", ip: "192.168.56.10"
  #config.vm.network 'forwarded_port', guest: 2375, host: 2375, id: 'dockerd'
  config.vm.synced_folder "/Users/rajibrath/VM_Config/vagrant_shared", "/home/mac_shared"
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ubuntu-vm'
    vb.memory = '9000'
    vb.cpus = '6'
  end
  config.vm.provision 'shell', path: 'provision.sh'

    # Configuration for Port Forwarding
    # Uncomment or add new ones here as required
    # config.vm.network 'forwarded_port', guest: 6379, host: 6379, id: 'redis'
    # config.vm.network 'forwarded_port', guest: 3306, host: 3306, id: 'mysql'
end
