apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/docker/mysql"  

