apiVersion: v1
kind: Pod
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  containers:
  - name: docker-mysql
    image: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_DATABASE
        value: "mydb"
      - name: MYSQL_ROOT_PASSWORD
        value: Lucifer
      - name: MYSQL_ROOT_HOST
        value: '%'
