apiVersion: v1
kind: Pod
metadata:
  name: hello-service
  labels:
    app: hello
spec:
  containers:
  - name: hello-service
    image: rajibrath/hello-service:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: owner.name
        value: "Rajib"
