apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-service
          image: rajibrath/hello-service:latest
          resources:
             limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: owner.name
              value: Rajib