apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  storageClassName: manual
  capacity:
    storage: 150M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/vagrant/mypv"  

