version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50000:50000
    container_name: my-jenkins
    volumes:
      - /home/mac_shared/container_volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock