apiVersion: v1
kind: Service
metadata:
  name: metadata-service-np
spec:
  type: NodePort
  selector:
    app: metadata
  ports:
  - nodePort: 32323
    port: 8090
    targetPort: 8090
    protocol: TCP
